import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import Hero from "@/components/Hero";
import Socials from "@/components/Socials";
import Footer from "@/components/Footer";
import Projects from "@/components/Projects";
import About from "@/components/About";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <main
      className={`flex min-h-screen flex-col   ${inter.className}`}>

        <Head>
          <title>Funmi's Folio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/myphoto.jpg" />
          </Head>
          <Socials/>
          <Hero/>
          <About/>
          <Projects/>
          <Contact/>
    </main>
    <Footer/>   

    </>
  );
}
